/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamRouteImport } from './routes/stream'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DiscussionsRouteImport } from './routes/discussions'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscussionsIndexRouteImport } from './routes/discussions.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as DiscussionsNewRouteImport } from './routes/discussions.new'
import { Route as DiscussionsIdRouteImport } from './routes/discussions.$id'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const StreamRoute = StreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsRoute = DiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscussionsIndexRoute = DiscussionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DiscussionsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const DiscussionsNewRoute = DiscussionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DiscussionsRoute,
} as any)
const DiscussionsIdRoute = DiscussionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DiscussionsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/discussions': typeof DiscussionsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/stream': typeof StreamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/discussions/$id': typeof DiscussionsIdRoute
  '/discussions/new': typeof DiscussionsNewRoute
  '/blog/': typeof BlogIndexRoute
  '/discussions/': typeof DiscussionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/profile': typeof ProfileRoute
  '/stream': typeof StreamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/discussions/$id': typeof DiscussionsIdRoute
  '/discussions/new': typeof DiscussionsNewRoute
  '/blog': typeof BlogIndexRoute
  '/discussions': typeof DiscussionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/discussions': typeof DiscussionsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/stream': typeof StreamRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/discussions/$id': typeof DiscussionsIdRoute
  '/discussions/new': typeof DiscussionsNewRoute
  '/blog/': typeof BlogIndexRoute
  '/discussions/': typeof DiscussionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/discussions'
    | '/profile'
    | '/stream'
    | '/blog/$slug'
    | '/discussions/$id'
    | '/discussions/new'
    | '/blog/'
    | '/discussions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/profile'
    | '/stream'
    | '/blog/$slug'
    | '/discussions/$id'
    | '/discussions/new'
    | '/blog'
    | '/discussions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/blog'
    | '/discussions'
    | '/profile'
    | '/stream'
    | '/blog/$slug'
    | '/discussions/$id'
    | '/discussions/new'
    | '/blog/'
    | '/discussions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  DiscussionsRoute: typeof DiscussionsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  StreamRoute: typeof StreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions': {
      id: '/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof DiscussionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discussions/': {
      id: '/discussions/'
      path: '/'
      fullPath: '/discussions/'
      preLoaderRoute: typeof DiscussionsIndexRouteImport
      parentRoute: typeof DiscussionsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/discussions/new': {
      id: '/discussions/new'
      path: '/new'
      fullPath: '/discussions/new'
      preLoaderRoute: typeof DiscussionsNewRouteImport
      parentRoute: typeof DiscussionsRoute
    }
    '/discussions/$id': {
      id: '/discussions/$id'
      path: '/$id'
      fullPath: '/discussions/$id'
      preLoaderRoute: typeof DiscussionsIdRouteImport
      parentRoute: typeof DiscussionsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DiscussionsRouteChildren {
  DiscussionsIdRoute: typeof DiscussionsIdRoute
  DiscussionsNewRoute: typeof DiscussionsNewRoute
  DiscussionsIndexRoute: typeof DiscussionsIndexRoute
}

const DiscussionsRouteChildren: DiscussionsRouteChildren = {
  DiscussionsIdRoute: DiscussionsIdRoute,
  DiscussionsNewRoute: DiscussionsNewRoute,
  DiscussionsIndexRoute: DiscussionsIndexRoute,
}

const DiscussionsRouteWithChildren = DiscussionsRoute._addFileChildren(
  DiscussionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  DiscussionsRoute: DiscussionsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  StreamRoute: StreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
